version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    user: root

  agent1:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent1
    networks:
      - jenkins-net
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_SECRET=d443fe8d613f874fa1e2ea45fcf7851474576740185d76955895c5813afb7bf2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

  agent2:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent2
    networks:
      - jenkins-net
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_SECRET=d1dc0c7dc148ce9a3e65af25c03133aac9d3e739a029f84a58f9b514654474b6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

  agent3:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent3
    networks:
      - jenkins-net
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent3
      - JENKINS_SECRET=7bffd9a593d777e2228532c69c660e47069adc4008e33dab25695316b32c2b57
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

networks:
  jenkins-net:
    driver: bridge