version: '3.8'

services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net
    user: root

  agent1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-agent1
    networks:
      - jenkins-net
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_SECRET=d4096efa8d13596577450eabdaf932f9a7408c4f26b22afb61d1c80a917cdd69
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

  agent2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-agent2
    networks:
      - jenkins-net
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_SECRET=ffe7610a82e2ea7bc2c3aae461a99ea3f3f1524d611b681e1e94525a8291b589
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

  agent3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-agent3
    networks:
      - jenkins-net
    environment:
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=agent3
      - JENKINS_SECRET=27ec6a3a6ea9ce1e857708b9ec962e6b7203d89871493fd80aad8a02b93e0001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins-master

networks:
  jenkins-net:
    driver: bridge